basePath: /
definitions:
  models.Item:
    properties:
      price:
        example: "1.25"
        type: string
      shortDescription:
        example: Pepsi - 12-oz
        type: string
    type: object
  models.Receipt:
    properties:
      id:
        example: f985a244-11e2-4f57-a451-d7147e6a76f8
        type: string
      items:
        items:
          $ref: '#/definitions/models.Item'
        type: array
      purchaseDate:
        example: "2022-01-01"
        type: string
      purchaseTime:
        example: "13:01"
        type: string
      retailer:
        example: Target
        type: string
      total:
        example: "1.25"
        type: string
    required:
    - purchaseDate
    - purchaseTime
    - retailer
    - total
    type: object
  models.ResponseGetPoints:
    properties:
      points:
        example: 56
        type: integer
    type: object
  models.ResponseProcessReceipts:
    properties:
      id:
        example: f985a244-11e2-4f57-a451-d7147e6a76f8
        type: string
    type: object
host: https://receipt-procesor-rafa-zamora.onrender.com
info:
  contact:
    name: Oswaldo Rafael Zamora Ramirez
    url: https://rafaelzamora.onrender.com/
  description: This is a API by Technical Test by Fetch
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Receipt Processor
  version: "1.0"
paths:
  /receipts/{id}/points:
    get:
      operationId: get-points
      parameters:
      - description: UUID of Receipt
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Total points of the Receipt
          schema:
            $ref: '#/definitions/models.ResponseGetPoints'
        "404":
          description: The Receipt does not exist
          schema:
            $ref: '#/definitions/models.ResponseGetPoints'
      summary: Calculate Points
      tags:
      - Receipts
  /receipts/process:
    post:
      operationId: receipts-process
      parameters:
      - description: Schema by Create New Receipt
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.Receipt'
      produces:
      - application/json
      responses:
        "200":
          description: UUID of Receipt
          schema:
            $ref: '#/definitions/models.ResponseProcessReceipts'
        "400":
          description: Error to proccess the Receipt
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: JSON body not is Valud missing fields
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Create new Receipt
      tags:
      - Receipts
swagger: "2.0"
